export default {
	INPUT_PLACE_HOLDER: '검색어를 입력하세요',
	HOME: '홈',
	POST: '등록된\n리스트',
	ISSUE: '이슈',
	TEMPLATE_COUNT: (value: string | number) => `${value}개`,
	MOVE_TO_GITHUB: 'GitHub으로 이동',
	MOVE_TO_ISSUE: 'Issue 보기',
	DELETE: '삭제하기',
	POST_ITEM: '등록하기',
	REPO_NAME: 'Repository 이름',
	ISSUE_NAME: 'Issue 여부',
	FORK_NUM: 'Fork 수',
	BUTTON: '버튼',
	IMAGE: '이미지',
	IS_POST: '등록여부',
};
